name = "toxicity-worker"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
workers_dev = true
zone_id = "xxx"
account_id = "xxx"
route = "toxicity.xxxxx.me/*"

[build]
command = "npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "TENSORFLOWDURABLE", class_name = "TensorflowDurable"}]
